# Generated by Django 6.0.4 on 2026-04-15 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/content/'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/content/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/course/'),
        ),
        migrations.AlterField(
            model_name='datacatalogue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/catalogue/'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/fellows/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/news/'),
        ),
        migrations.AlterField(
            model_name='policybrief',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/policy/'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/seminar/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/people/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/trainings/'),
        ),
    ]
