# Generated by Django 6.0.4 on 2026-04-18 07:07

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datacatalogue',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratelimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
