# Generated by Django 6.0.4 on 2026-04-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_content_id_alter_contentsection_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentsection',
            new_name='content_sec_content_a6aa21_idx',
            old_name='content_sec_content_393b04_idx',
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content',
            field=models.ForeignKey(db_column='contentId', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='config.content'),
        ),
    ]
