# Generated by Django 6.0.4 on 2026-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_content_sec_content_393b04_idx_content_sec_content_a6aa21_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='content',
            new_name='content_authorI_72c716_idx',
            old_name='content_author__6c08b4_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='author_name',
            field=models.CharField(blank=True, db_column='authorId', max_length=255, null=True),
        ),
    ]
