# Generated by Django 6.0.4 on 2026-04-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_course_created_by_fellowship_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_authorI_72c716_idx',
        ),
        migrations.AddField(
            model_name='content',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['author_name'], name='content_author__6c08b4_idx'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
    ]
