# Generated by Django 6.0.4 on 2026-04-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_rename_content_author__6c08b4_idx_content_authori_72c716_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='report',
            field=models.ForeignKey(db_column='reportId', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='config.report'),
        ),
    ]
