# Generated by Django 6.0.4 on 2026-04-18 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_download_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdById', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_published',
            field=models.DateTimeField(blank=True, db_column='datePublished', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='drive_link',
            field=models.URLField(blank=True, db_column='driveLink', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_name',
            field=models.CharField(db_column='fileName', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_size',
            field=models.IntegerField(blank=True, db_column='fileSize', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_type',
            field=models.CharField(blank=True, db_column='fileType', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(db_column='isPublic', default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='year_published',
            field=models.IntegerField(blank=True, db_column='yearPublished', null=True),
        ),
    ]
