# Generated by Django 6.0.4 on 2026-04-17 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_contactform_id_alter_contentsection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'PDF Document'), ('VIDEO', 'Video Link'), ('DOCUMENT', 'Document')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='site/trainings/media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/images/trainings/sections/')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'training_sections',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='training',
            name='image',
        ),
        migrations.AddField(
            model_name='training',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='date_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='external_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='training',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='training',
            name='upcoming',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['upcoming'], name='trainings_upcomin_3d5063_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['category'], name='trainings_categor_9206b6_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['featured'], name='trainings_feature_a5dce5_idx'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='config.training'),
        ),
        migrations.AddField(
            model_name='trainingsection',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='config.training'),
        ),
    ]
