# Generated by Django 6.0.4 on 2026-04-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_report_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowship',
            name='custom_dept',
        ),
        migrations.RemoveField(
            model_name='fellowship',
            name='custom_email',
        ),
        migrations.RemoveField(
            model_name='fellowship',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='fellowship',
            name='custom_title',
        ),
    ]
