# Generated by Django 6.0.4 on 2026-04-19 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_remove_fellowship_custom_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/images/careers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='site/files/careers/')),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('show', models.BooleanField(db_index=True, default=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careers',
                'indexes': [models.Index(fields=['is_open'], name='careers_is_open_217ba8_idx'), models.Index(fields=['show'], name='careers_show_70a620_idx'), models.Index(fields=['deadline'], name='careers_deadlin_6b8d5a_idx')],
            },
        ),
    ]
