# Generated by Django 6.0.4 on 2026-04-22 06:55

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacatalogueview',
            name='id',
            field=models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
