# Generated by Django 6.0.4 on 2026-06-24 12:52

import config.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.CharField(default=config.models.generate_cuid, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='site/images/library/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
