# Generated by Django 6.0.4 on 2026-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_siteimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='training',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='training',
            name='t_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/images/trainings/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['is_public'], name='trainings_is_publ_accf4c_idx'),
        ),
    ]
