# Generated by Django 6.0.4 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_alter_training_options_training_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
